<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\SourceCraftRepoHealthChecker.Application\SourceCraftRepoHealthChecker.Application.csproj" />
      <ProjectReference Include="..\SourceCraftRepoHealthChecker.Domain\SourceCraftRepoHealthChecker.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
