// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SourceCraftRepoHealthChecker.infrastructure.Persistence;

#nullable disable

namespace SourceCraftRepoHealthChecker.infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepoHealthCheckerDbContext))]
    [Migration("20260926075735_AddMetricScoresUserTokenAndRecommendationDetails")]
    partial class AddMetricScoresUserTokenAndRecommendationDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("DataStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<long>("StartedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId");

                    b.ToTable("AnalysisRuns");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.CategoryScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("DataStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("CategoryScores");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.MetricScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<int>("DataStatus")
                        .HasColumnType("integer");

                    b.Property<double>("NormalizedScore")
                        .HasColumnType("double precision");

                    b.Property<double>("RawValue")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("MetricScores");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ExpectedImpact")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WhyImportant")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AnalyzedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("LastActivityAt")
                        .HasColumnType("bigint");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceCraftId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("SourceCraftId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceCraftToken")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("YaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("YaId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.UserAi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiBaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("AiProvider")
                        .HasColumnType("integer");

                    b.Property<string>("AiToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserAis");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.AnalysisRun", b =>
                {
                    b.HasOne("SourceCraftRepoHealthChecker.Domain.Entities.Repository", null)
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SourceCraftRepoHealthChecker.Domain.Entities.User", null)
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.CategoryScore", b =>
                {
                    b.HasOne("SourceCraftRepoHealthChecker.Domain.Entities.AnalysisRun", null)
                        .WithMany("CategoryScores")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.MetricScore", b =>
                {
                    b.HasOne("SourceCraftRepoHealthChecker.Domain.Entities.AnalysisRun", null)
                        .WithMany("Metrics")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("SourceCraftRepoHealthChecker.Domain.Entities.AnalysisRun", null)
                        .WithMany("Recommendations")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.UserAi", b =>
                {
                    b.HasOne("SourceCraftRepoHealthChecker.Domain.Entities.User", null)
                        .WithOne("Ai")
                        .HasForeignKey("SourceCraftRepoHealthChecker.Domain.Entities.UserAi", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.AnalysisRun", b =>
                {
                    b.Navigation("CategoryScores");

                    b.Navigation("Metrics");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.Repository", b =>
                {
                    b.Navigation("AnalysisRuns");
                });

            modelBuilder.Entity("SourceCraftRepoHealthChecker.Domain.Entities.User", b =>
                {
                    b.Navigation("Ai");

                    b.Navigation("AnalysisRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
